### ISSUE TITLE
Checklist Exercise

### ISSUE THREAD

**Issue by joelvitorniino** [joelvitorniino/course-java#1]
- [x] Create Class Order
- [x] Create Class Client
- [x] Create Class OrderItem
- [x] Create Class Product
- [x] Create Enum OrderStatus
- [x] Create Main Class Program
